In [1]:
import numpy as np

In [2]:
x = np.array([10, 20, 30])
x.shape

(3,)

In [5]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
y = x.reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
y.shape

(3, 3)

In [11]:
# Access a row completely based on position
y[0,:] # First row all columns

array([0, 1, 2])

In [13]:
y[:,0] # All rows but first column alone

array([0, 3, 6])

In [16]:
y[0:2, :] # Access first two rows and all columns

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
y[:,(0,2)] # Access all rows in column one & three

array([[0, 2],
       [3, 5],
       [6, 8]])

In [18]:
import pandas as pd
odi = pd.read_csv('odi-batting.csv')
odi.shape

(55926, 8)

In [19]:
odi.columns

Index(['Country', 'Player', 'Runs', 'ScoreRate', 'MatchDate', 'Ground',
       'Versus', 'URL'],
      dtype='object')

In [21]:
odi.describe().columns # All numerical column names

Index(['Runs', 'ScoreRate'], dtype='object')

In [23]:
odi._get_numeric_data().columns # All numerical column names

Index(['Runs', 'ScoreRate'], dtype='object')

In [25]:
odi.describe(include='object').columns # All non-numerical column names

Index(['Country', 'Player', 'MatchDate', 'Ground', 'Versus', 'URL'], dtype='object')

In [26]:
all_columns = odi.columns # All column names
num_columns = odi.describe().columns # Numerical column names
non_num_columns = np.setdiff1d(all_columns, num_columns)
non_num_columns

array(['Country', 'Ground', 'MatchDate', 'Player', 'URL', 'Versus'],
      dtype=object)

In [27]:
import datetime

In [63]:
x = list(range(100000000))
y = list(range(100000000))
start = datetime.datetime.now()
# len(x + y)
z = [x[i]-y[i] for i in range(100000000)]
end = datetime.datetime.now()
time_taken_python = (end - start).microseconds

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-63-753dc75592ca>", line 5, in <module>
    z = [x[i]-y[i] for i in range(100000000)]
  File "<ipython-input-63-753dc75592ca>", line 5, in <listcomp>
    z = [x[i]-y[i] for i in range(100000000)]
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2033, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 1095, in get_records
    return _fixed_get

KeyboardInterrupt: 

In [64]:
x = np.arange(100000000)
y = np.arange(100000000)
start = datetime.datetime.now()
z = x - y
end = datetime.datetime.now()
time_taken_numpy = (end - start).microseconds
time_taken_numpy

KeyboardInterrupt: 

In [65]:
time_taken_numpy / time_taken_python

0.08329852117971426

### Sorting

In [86]:
np.random.seed(0)
x = np.random.randint(1,10,5) # Randomly select 5 elements between 1 to 10
x

array([6, 1, 4, 4, 8])

In [87]:
np.sort(x) # Ascending sorting

array([1, 4, 4, 6, 8])

In [88]:
np.sort(x)[::-1] # Descending sorting; [::-1] is used for reversing a list

array([8, 6, 4, 4, 1])

In [90]:
x

array([6, 1, 4, 4, 8])

In [92]:
np.argmax(x) # Index in which x has maximum value

4

In [93]:
np.argmin(x) # Index in which x has minimum value

1

In [94]:
x

array([6, 1, 4, 4, 8])

In [95]:
x.argsort()

array([1, 2, 3, 0, 4], dtype=int64)

In [96]:
np.max(x)

8

In [97]:
np.argmax(x)

4

In [99]:
x.argsort().argsort() # Rank of each element; Minimum value will get rank 0

array([3, 0, 1, 2, 4], dtype=int64)

### 3-D arrays

In [103]:
x = np.arange(8).reshape(2,2,2)
x.shape

(2, 2, 2)

In [106]:
x[:,:,0] # All rows & all columns in the first dimension

array([[0, 2],
       [4, 6]])

In [107]:
x[:,:,1] # All rows & all columns in the second dimension

array([[1, 3],
       [5, 7]])

In [108]:
x33 = np.arange(27).reshape(3,3,3)
x33

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [110]:
x33[:,:,1]

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [111]:
x33[1,2,1]

16

## Stacking functions

In [113]:
x1 = np.arange(10)
y1 = np.arange(10,20,1)
print(x1)
print(y1)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [114]:
np.hstack([x1, y1])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [115]:
np.vstack([x1, y1])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [116]:
## Two dimension

In [119]:
x2 = np.arange(4).reshape(2,2)
y2 = np.arange(10,14,1).reshape(2,2)
print(x2.shape, y2.shape)
print('-----')
print(x2)
print('-----')
print(y2)

(2, 2) (2, 2)
-----
[[0 1]
 [2 3]]
-----
[[10 11]
 [12 13]]


In [120]:
np.hstack([x2,y2])

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [121]:
np.vstack([x2, y2])

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [122]:
np.column_stack([x2, y2])

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [126]:
np.dstack([x2,y2]).shape

(2, 2, 2)

In [124]:
y2

array([[10, 11],
       [12, 13]])

In [127]:
## Splitting arrays

In [129]:
x1 = np.arange(10)
print(x1)

[0 1 2 3 4 5 6 7 8 9]


In [130]:
np.split(x1, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [132]:
y1 = np.arange(11)
np.array_split(y1,2)

[array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [133]:
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
np.array_split(x1, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [136]:
np.array_split(x1, (2,4,8))

[array([0, 1]), array([2, 3]), array([4, 5, 6, 7]), array([8, 9])]

In [18]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x[x>5] = 10
x

array([ 0,  1,  2,  3,  4,  5, 10, 10, 10, 10])

In [20]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
y = np.array([1,2,3])
y

array([1, 2, 3])

In [11]:
y.shape

(3,)

In [12]:
y.T.shape

(3,)

In [16]:
x - y.reshape(3,1)

array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6]])

In [4]:
np.set_printoptions(threshold=3)
x

array([ 0,  1,  2, ..., 97, 98, 99])

In [5]:
x

array([ 0,  1,  2, ..., 97, 98, 99])

In [6]:
x > 5

array([False, False, False, ...,  True,  True,  True])